"""
RIT Market Simulator Algorithmic ETF Arbitrage Case - Support File
Rotman BMO Finance Research and Trading Lab, Uniersity of Toronto (C)
All rights reserved.
"""

import requests
from time import sleep
import numpy as np
import math

'''
If you are not familiar with Python or feeling a little bit rusty, highly recommend you to go through the following link:
    https://github.com/trekhleb/learn-python

If you have any question about REST APIs and outputs of code please read:
    https://realpython.com/api-integration-in-python/#http-methods
    https://rit.306w.ca/RIT-REST-API/1.0.3/?port=9999&key=Rotman#/

So bascially：
The core of this case is to design algorithmic trading strategies that exploit arbitrage opportunities between the ETF (RITC) 
and its underlying stocks (BULL and BEAR), while effectively using tender offers and conversion tools to avoid speculative risk
and maximize returns.
'''

API = "http://localhost:9999/v1"
API_KEY = "Rotman"                     # <-- your key
HDRS = {"X-API-key": API_KEY}          # change to X-API-Key if your server needs it

# Tickers
CAD  = "CAD"    # currency instrument quoted in CAD
USD  = "USD"    # price of 1 USD in CAD (i.e., USD/CAD)
BULL = "BULL"   # stock in CAD
BEAR = "BEAR"   # stock in CAD
RITC = "RITC"   # ETF quoted in USD

# Per problem statement
FEE_MKT = 0.02           # $/share (market)
REBATE_LMT = 0.01        # $/share (passive) - not used in this baseline
MAX_SIZE_EQUITY = 10000 # per order for BULL/BEAR/RITC
MAX_SIZE_FX = 2500000  # per order for CAD/USD

# Basic risk guardrails (adjust as needed)
MAX_LONG_NET  = 250000
MAX_SHORT_NET = -250000
MAX_GROSS     = 500000
ORDER_QTY     = 5000    # child order size for arb legs

# Cushion to beat fees & slippage.
# 3 legs with market orders => ~0.06 CAD/sh cost; add a bit more for safety.
ARB_THRESHOLD_CAD = 0.07

# --------- SESSION ----------
s = requests.Session()
s.headers.update(HDRS)

# --------- HELPERS ----------
def get_tick_status():
    # Gets simulation status (active or stopped) for the tick
    r = s.get(f"{API}/case")
    r.raise_for_status()
    j = r.json()
    return j["tick"], j["status"]

def best_bid_ask(ticker):
    # Returns best bid and ask prices for a ticker
    r = s.get(f"{API}/securities/book", params={"ticker": ticker})
    r.raise_for_status()
    book = r.json()
    'Why choose [0] here, not [1]? Is the price for bids and asks also generated by r'
    bid = float(book["bids"][0]["price"]) if book["bids"] else 0.0
    ask = float(book["asks"][0]["price"]) if book["asks"] else 1e12
    return bid, ask

def positions_map(call):
    # Tracks current positions (number of shares currently hold for a ticker/instrument), to help risk management
    r = s.get(f"{API}/securities") # after switching /positions to /securities, no error popup.
    r.raise_for_status()
    out = {p["ticker"]: int(p.get("position", 0)) for p in r.json()}
    unrealized = {p["ticker"]: int(p.get("unrealized", 0)) for p in r.json()}
    for k in (BULL, BEAR, RITC, USD, CAD):
        out.setdefault(k, 0)
        unrealized.setdefault(k, 0)
    if call == "out":
        return out
    elif call == "unrealized":
        return unrealized

def place_mkt(ticker, action, qty): 
    # Sends Market orders; price param is ignore by most RIT cases when type=MARKET
    return s.post(f"{API}/orders",
                  params={"ticker": ticker, "type": "MARKET",
                          "quantity": int(qty), "action": action}).ok

def within_limits():
    # Simple gross/net guard using equity legs only
    pos = positions_map("out")
    gross = abs(pos[BULL]) + abs(pos[BEAR]) + abs(pos[RITC])
    net   = pos[BULL] + pos[BEAR] + pos[RITC]  # simple net; refine as desired
    return (gross < MAX_GROSS) and (MAX_SHORT_NET < net < MAX_LONG_NET)

def accept_active_tender_offers():
    # Retrieve active tender offers from the RIT API, and accept the offer
    r = s.get(f"{API}/tenders")  # replace with the correct endpoint
    r.raise_for_status()
    offers = r.json()
        
    if offers:
        tender_id = offers[0]['tender_id']
        price = offers[0]['price']
        if offers[0]['is_fixed_bid']:
            resp = s.post(f"{API}/tenders/{tender_id}")
        else:
            resp = s.post(f"{API}/tenders/{tender_id}", params={"price": price})
        return print("Tender Offer Accepted:", resp.ok)
    print("No active tenders")

# --------- CORE LOGIC ----------
def step_once():
    # Get executable prices
    bull_bid, bull_ask = best_bid_ask(BULL)
    bear_bid, bear_ask = best_bid_ask(BEAR)
    ritc_bid_usd, ritc_ask_usd = best_bid_ask(RITC)
    usd_bid, usd_ask = best_bid_ask(USD)   # USD quoted in CAD (USD/CAD)

    # Convert RITC to CAD using USD book
    ritc_bid_cad = ritc_bid_usd * usd_bid
    ritc_ask_cad = ritc_ask_usd * usd_ask

    # Basket executable values in CAD
    basket_sell_value = bull_bid + bear_bid      # what we get if we SELL basket now
    basket_buy_cost   = bull_ask + bear_ask      # what we pay if we BUY basket now

    # Direction 1: Basket rich vs ETF
    # SELL basket (hit bids), BUY RITC in USD (lift ask) -> compare in CAD
    edge1 = basket_sell_value - ritc_ask_cad

    # Direction 2: ETF rich vs Basket
    # SELL RITC (hit bid in USD), BUY basket (lift asks) -> compare in CAD
    edge2 = ritc_bid_cad - basket_buy_cost
    
    #accept_active_tender_offers() # Automatically checking and acceptting all of the tender offer

  
    def tender_offers_valid():
        r = s.get(f"{API}/tenders")  # replace with the correct endpoint
        r.raise_for_status()
        offers = r.json()
        print(offers)

        if offers:
            price = offers[0]['price']
            quantity = offers[0]['quantity']
            action = offers[0]['action']

            if action == "BUY":
                print('pass')
                if basket_sell_value - price >= ARB_THRESHOLD_CAD:
                    place_mkt(BULL, "SELL", quantity)
                    place_mkt(BEAR, "SELL", quantity)
                    print("accepted offer")
                    return True
            elif action == "SELL":
                print('pass')
                if price - basket_buy_cost >= ARB_THRESHOLD_CAD:
                    place_mkt(BULL, "BUY", quantity)
                    place_mkt(BEAR, "BUY", quantity)
                    print("accepted offer")
                    return True
            print("declined offer")
        return False

    if tender_offers_valid():
        accept_active_tender_offers() # Automatically checking and acceptting all of the tender offer

    traded = False
    
    if edge1 >= ARB_THRESHOLD_CAD and within_limits():
        # Basket rich: sell BULL & BEAR, buy RITC
        q1 = order_size(edge1)
        place_mkt(BULL, "SELL", q1)
        place_mkt(BEAR, "SELL", q1)
        place_mkt(RITC, "BUY",  q1)
        traded = True

    elif edge2 >= ARB_THRESHOLD_CAD and within_limits():
        # ETF rich: buy BULL & BEAR, sell RITC
        q2 = order_size(edge2)
        place_mkt(BULL, "BUY",  q2)
        place_mkt(BEAR, "BUY",  q2)
        place_mkt(RITC, "SELL", q2)
        traded = True
    
   
    return traded, edge1, edge2, {
        "bull_bid": bull_bid, "bull_ask": bull_ask,
        "bear_bid": bear_bid, "bear_ask": bear_ask,
        "ritc_bid_usd": ritc_bid_usd, "ritc_ask_usd": ritc_ask_usd,
        "usd_bid": usd_bid, "usd_ask": usd_ask,
        "ritc_bid_cad": ritc_bid_cad, "ritc_ask_cad": ritc_ask_cad
    }

def mid_price(ticker):
    bid, ask = best_bid_ask(ticker)
    if bid == 0.0 and ask == 1e12:
        return None
    print
    return 0.5 * (bid + ask)

def main():


    def moving_avg(stk, ma_yest, days):
        price = mid_price(stk)
        if price is None:
            return ma_yest  # don't break if book empty

        alpha = 2 / (days + 1)  # smoothing factor
        return alpha * price + (1 - alpha) * ma_yest
    

    def order_size(stk, delta):
        
        pos   = positions_map("out")
        gross = abs(pos[BULL]) + abs(pos[BEAR]) + 2*abs(pos[RITC])
        net   = pos[BULL] + pos[BEAR] + 2*pos[RITC]

        base   = MAX_SIZE_EQUITY
        scalar = 14000
        max_sz = MAX_SIZE_EQUITY

        GROSS_LIMIT = MAX_GROSS
        NET_LIMIT   = 250000 

        if stk == "USD":
            gross = abs(pos["USD"])
            net = post["USD"]

            NET_LIMIT = 50000000
            GROSS_LIMIT = 50000000

            base = 2500000
            scalar = scalar * 100
            max_sz = 2500000


        raw_size = base + scalar * abs(delta)  


        net_usage = (abs(net) / NET_LIMIT) + 0.25
        net_scale = max(0.0, 1.0 - net_usage)

   
        size_scale =  net_scale

   
        size = int(raw_size * size_scale)

        size = min(size, max_sz)

        if size < max_sz/20:
            size = max_sz/20

        return size


    def profit_take(stk):
        # Get full portfolio dictionary
      

        position = positions_map("out")[stk]      # int
        unrealized =  positions_map("unrealized")[stk]



        if position == 0 or unrealized is None:
            return

        # Profit-taking threshold
        target_gain = 0.43   # 50% return
        target_loss = -0.28  # 30% loss ROI

        # Actual return
        pnl_pct = unrealized/abs(position)


        # If profit % exceeds threshold → exit
        if pnl_pct >= target_gain and unrealized >= 10000:

            if position > 0:
                place_mkt(stk, "SELL", abs(position))
                #print('profittaken1112211112222111111')
         

            elif position < 0:
                place_mkt(stk, "BUY", abs(position))
                #print('profittaken11111111222222')

        if pnl_pct <= target_loss and unrealized <= -10000:

            if position > 0:
                place_mkt(stk, "SELL", abs(position))
                #print('profitloss2222222222')
         

            elif position < 0:
                place_mkt(stk, "BUY", abs(position))
                #print('profitloss111111111')

    ma_list_s = {USD: [mid_price(USD)] * 10}  # list of historical moving averages, long
    ma_list_l = {USD: [mid_price(USD)] * 10}
    ma_list_d = {USD: [mid_price(USD)] * 10}
    ma_s = {USD: 0}  # moving averages
    ma_l = {USD: 0}  # moving averages
    ma_d = {USD: 0}  # moving averages
    days_s = 30  # Amount of days short moving average is calculated on
    days_l = 60  # Amount of days long moving average is calculated on
    ticks = 0
    growth_threshold_up = 0.002  # Average difference in moving average required to justify trade
    growth_threshold_down = -0.002  # Average difference in moving average required to justify trade
    previous_tick = -1

    # Run while case active

    tick, status = get_tick_status()
    while status == "ACTIVE":
        step_once()
        # Optional: print a lightweight heartbeat every 1s
        #print(f"tick={tick} e1={e1:.4f} e2={e2:.4f} ritc_ask_cad={info['ritc_ask_cad']:.4f}")


        mid_USD = mid_price(USD)

        stock_mid = {USD: mid_USD }  # mid bid/ask price of stocks

        for i in [USD]:

    
            ma_s[i] = moving_avg(i, ma_list_s[i][-1], days_s)
            print(ma_s[i])
            ma_l[i] = moving_avg(i, ma_list_l[i][-1], days_l)
            print(ma_l[i])
            ma_d[i] = moving_avg(i, ma_list_d[i][-1], 10)

            ma_list_s[i].append(ma_s[i])
            ma_list_l[i].append(ma_l[i])
            ma_list_d[i].append(ma_d[i])
           
            
            
            ma_delta = ma_s[i]-ma_l[i]


            upper_band = 0 
            lower_band = 0
            window = 15
            

            if len(ma_list_d[i]) >= window:
                data = ma_list_d[i][-window:] 

                mean = np.mean(data)
                stdev = np.std(data)

                upper_band = mean + 2 * stdev
                lower_band = mean - 2 * stdev

          
            def trade(i):
                macd = ma_delta
                repeat = 1

                qty = order_size(i, ma_delta)
            
                if abs(macd) >= 0.1:
                    qty = 10000
                    repeat = 2

                #LONG ENTRY

                if ma_s[i] > ma_l[i] and macd > growth_threshold_up:
                    qty = order_size(i, ma_delta)
                    for j in range(repeat):
                        place_mkt(i, "BUY", qty)
                        print("buy" , qty)

                #SHORT ENTRY
                elif ma_s[i] < ma_l[i] and macd < growth_threshold_down:
                    qty = order_size(i, ma_delta)
                    for j in range(repeat):
                        place_mkt(i, "SELL", qty)
                        print("sell" , qty)

            if tick >= 13 and tick != previous_tick:
                trade(i)
                profit_take(i)
                
          
        
        previous_tick = tick
        sleep(0.2)
        tick, status = get_tick_status()
        ticks += 1

if __name__ == "__main__":
    main()
